yandex:
  oauth:
    client-id: 5948803baad7427e83cfadbf40cc9c52
    client-secret: 5fb986471cf541d18135531ef16f152a
    redirect-uri: http://localhost:8090/oauth/yandex/callback
    auth-url: https://oauth.yandex.ru/authorize
    token-url: https://oauth.yandex.ru/token