yandex:
  oauth:
    client-id: e8134c084380492a8ce12ddb2296a04f
    client-secret: 12c1cb5b7631482fa1f3a33878250e3f
    redirect-uri: http://localhost:8080/oauth/yandex/callback
    auth-url: https://oauth.yandex.ru/authorize
    token-url: https://oauth.yandex.ru/token